### ISSUE TITLE
Load Plugins and Spawn scripts

### ISSUE THREAD

**Issue by gabeduke** [PHLAK/docker-hangoutsbot#2]
Have you considered a way to load plugins & spawn scripts? I've started playing with an idea how to implement.

something like:
- [ ] Add git to the base image
- [ ] User would `docker cp` a file that contains git urls for the plugins/spawns they want to load to the container. An alternative would be to mount a folder with the folders already in place
- [ ] modify the startup cmd by adding a script to the container startup cmd that looks for either the file or mount dir.
    * If the file with git urls is discovered pull in the git repos to hangouts plugins dir, & spawn files to a bin dir. 
    * If a mounted directory: `cp host_volume/plugins /etc/hangoutsbot/plugins` and `cp host_volume/spawns /etc/hangoutsbot/spawns` 
    * Then symlink folders in the volume to the hangoutsbot location.
    * Finally `pip install -r` any requirements in the two folders

Any concerns? is there simpler way to achieve this? Does this add too long to startup?

Bonus: as a potential solution to #1 a list of system packages could be passed to the container as well.

**Comment by PHLAK** [comment]
@gabeduke For adding your own plugins and other files you can create your own `Dockerfile` that extends the `phlak/hangoutsbot` image and build a new image.

    FROM phlak/hangoutsbot:2.8.0

    USER root

    # Add your custom plugins
    COPY plugins/* /opt/hangoutsbot/hangupsbot/plugins/
    RUN chown -R hangoutsbot:hangoutsbot /opt/hangoutsbot/hangupsbot/plugins/

    USER hangoutsbot

Then build your new image.

    docker build --force-rm --pull --tag gabeduke/hangoutsbot .

You can then use this new image by using `gabeduke/hangoutsbot` instead of `phlak/hangoutsbot` in your docker commands.

I have done this [here](https://github.com/TheInnerCircleO/docker-icbot/blob/master/Dockerfile) for example.

**Comment by gabeduke** [comment]
Well that is certainly a lot simpler! Thanks!
